#############################
#                           #
#      RELEASE SECTION      #
#                           #
#############################

# Name of the Linux distribution if you wanna make a SplashOS based distro.
release_name: SplashOS

# Version of the build 
release_version: 0.0.1

# Codename for this build
release_codename: Kokomi

# release cycle
# Choice the following options:
#   - release
#   - rc
#   - beta
#   - alpha
#   - pre-alpha 
release_cycle: pre-alpha


#############################
#                           #
#        PATH SECTION       #
#                           #
#############################

# What type of location should SplashOS build in?
# Choice the following options:
#   - directory 
#   - partition (recommended)
path_type: directory

# What partition should be mounted?
# Note: only required when path_type is set on "partition"
path_device: /dev/null

# The path where SplashOS should be build in
# When path_type is set on the "partition" the "path_device" will be mounted on that location.
path_build: /mnt/splashos


#############################
#                           #
#      OUTPUT SECTION       #
#                           #
#############################

# Enable or Disable to export as a single file.
output_makefile: false

# What type of file should be exported from the output?
# Choice the following options:
#   - iso(recommended): can be used on a vm or bare metal.
#   - vmdk: for a vmware virtual machine
#   - vdi: for a virtualbox virtual machine
#   - qcow2: for a qemu virtual machine
output_filetype: iso

# Where should we export the file? 
output_path: .


#############################
#                           #
#       BUILD SECTION       #
#                           #
#############################

# Using precompiled binaries instead of fully compiling from source.
# Setting this on true will result in faster building
build_useprecompiled: false

# Build target for spesific architecture
# Choice the following options:
#    - amd64 (recommended): For x86_64 cpu's
#    - arm64: For ARM cpu's
build_arch: amd64

# The edition configuration used.
# Choice the following options:
#     - molecule: a minimal edition that is used as base for any other edition, molecule alone can be used for IOT devices.
#     - desktop: Designed for your average non-technical user, uses GNOME shell with custom theme.
build_edition: molecule
